-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Create the database
CREATE DATABASE IF NOT EXISTS REAL_ESTATE;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS REAL_ESTATE.STAGING;
CREATE SCHEMA IF NOT EXISTS REAL_ESTATE.ANALYTICS;

-- Create a warehouse (auto-suspend after 60s to minimize cost)
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create a service account role for the pipeline
CREATE ROLE IF NOT EXISTS PIPELINE_ROLE;

-- Create a service account user
CREATE USER IF NOT EXISTS pipeline_user
  DEFAULT_ROLE = PIPELINE_ROLE
  DEFAULT_WAREHOUSE = TRANSFORM_WH;

GRANT ROLE PIPELINE_ROLE TO USER pipeline_user;
