-- Create the database
CREATE DATABASE REAL_ESTATE;

-- Create schemas
CREATE SCHEMA REAL_ESTATE.RAW;
CREATE SCHEMA REAL_ESTATE.STAGING;
CREATE SCHEMA REAL_ESTATE.ANALYTICS;

-- Create a warehouse (auto-suspend after 60s to minimize cost)
CREATE WAREHOUSE TRANSFORM_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create a service account role for the pipeline
CREATE ROLE PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE PIPELINE_ROLE;
GRANT ALL ON DATABASE REAL_ESTATE TO ROLE PIPELINE_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE REAL_ESTATE TO ROLE PIPELINE_ROLE;

-- Create a service account user
CREATE USER pipeline_user
  PASSWORD = '<STRONG_PASSWORD>'
  DEFAULT_ROLE = PIPELINE_ROLE
  DEFAULT_WAREHOUSE = TRANSFORM_WH;
GRANT ROLE PIPELINE_ROLE TO USER pipeline_user;