-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Warehouse
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE PIPELINE_ROLE;

-- Database
GRANT USAGE ON DATABASE REAL_ESTATE TO ROLE PIPELINE_ROLE;

-- Schemas
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE SEQUENCE
  ON SCHEMA REAL_ESTATE.STAGING TO ROLE PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE SEQUENCE
  ON SCHEMA REAL_ESTATE.ANALYTICS TO ROLE PIPELINE_ROLE;

-- Tables (run after tables are created)
GRANT ALL ON ALL TABLES IN SCHEMA REAL_ESTATE.STAGING TO ROLE PIPELINE_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA REAL_ESTATE.ANALYTICS TO ROLE PIPELINE_ROLE;

-- Sequences
GRANT ALL ON ALL SEQUENCES IN SCHEMA REAL_ESTATE.ANALYTICS TO ROLE PIPELINE_ROLE;

-- Storage integration and stage
GRANT USAGE ON INTEGRATION S3_INTEGRATION TO ROLE PIPELINE_ROLE;
GRANT USAGE ON STAGE REAL_ESTATE.STAGING.S3_STAGE TO ROLE PIPELINE_ROLE;
