CREATE STORAGE INTEGRATION IF NOT EXISTS s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<SNOWFLAKE_IAM_ROLE_ARN>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET_NAME>/staging/');

CREATE STAGE IF NOT EXISTS REAL_ESTATE.STAGING.s3_stage
  STORAGE_INTEGRATION = s3_integration
  URL = 's3://<BUCKET_NAME>/staging/'
  FILE_FORMAT = (TYPE = PARQUET);